site_name: Outdoor

theme:
  name: terminal
  language: de

markdown_extensions:
  - admonition

plugins:
  - search

use_directory_urls: false

repo_url: https://github.com/herr-nm/Privat_Outdoor

site_url: https://herr-nm.github.io/Privat_Outdoor

nav:
    - Tourenübersicht: 'index.md'
    - 2025:
      Zugspitze: '2025/zugspitze.md'
