site_name: Outdoor

theme:
  name: terminal
  language: de

markdown_extensions:
  - admonition

plugins:
  - search

nav:
  - Tourenübersicht: 'index.md'
  - 2025:
      - Zugspitze: '2025/zugspitze.md'
  - 2024:
  - 2023:
      - Zugspitze: '2025/zugspitze.md'
  - 2022:
      - Zugspitze: '2025/zugspitze.md'